### ISSUE TITLE
deprecated selectors :host and ::shadow

### ISSUE THREAD

**Issue by ghost** [jonsamp/codecademy-syntax#1]
this "depreciation" issue lies in index.less, but I am not able to resolve it myself
Atom version is 1.14.3
your syntax version is 0.5.0
please help!

![screen shot 2017-02-22 at 14 02 51](https://cloud.githubusercontent.com/assets/13712320/23229927/b47f6cf8-f907-11e6-8db5-708e50ce342a.png)

**Comment by jonsamp** [comment]
@tripscripts this is fixed! Please update when you get a chance.
