### ISSUE TITLE
Syntax Highlighting not changing

### ISSUE THREAD

**Issue by taytay139** [jonsamp/codecademy-syntax#2]
I want to change to the Codecademy syntax theme from the Solarized Dark Atom theme. However, only the background color changes but the actual syntax highlighting stays the same. It's really frustrating. Do you know what the problem could be? I'll attach some screenshots below:

This is what my current theme looks like:

![2](https://user-images.githubusercontent.com/26188967/29980683-61bec7e4-8f10-11e7-9193-86e74b4f5ee7.png)

![3](https://user-images.githubusercontent.com/26188967/29980692-669c22f2-8f10-11e7-8401-1465fedec9b4.png)

This is what it looks like when I try to change to the Codecademy theme (as you can see it doesn't appear to work except for the background color):

![4](https://user-images.githubusercontent.com/26188967/29980695-6ddbd2d8-8f10-11e7-8a03-5cd6522ff870.png)

![5](https://user-images.githubusercontent.com/26188967/29980699-71b2150c-8f10-11e7-9d6c-8a0b59ecf065.png)

**Comment by jonsamp** [comment]
That's interesting behavior. I also see that the gutter does not change on the left of the editor pane. Did you try restarting Atom? Also, are you on the latest version of Atom? 

I just switched to Solarized Dark, then back the Codecademy, and it is highlighting correctly. Does this issue only occur with the Codecademy syntax theme for you?

**Comment by taytay139** [comment]
I have restarted and I also have the latest version, but it still doesn't work. It appears the issue also occurs with other downloaded themes, but not the built in ones. Would you still be able to help me?

Thanks!

**Comment by taytay139** [comment]
Would you still be able to help me?? I haven't found any solution to this problem online so far.

**Comment by taytay139** [comment]
Now all of a sudden the text is all white when I change to a downloaded syntax theme, but now the background changes completely, including the gutter. Any suggestions?

**Comment by jonsamp** [comment]
I am not sure what's going on. I am not able to replicate this behavior on my machine, and it sounds like this might be an issue with Atom.

I would suggest posting this as an issue on [Atom's issues](https://github.com/atom/atom/issues).

Hope this helps, closing this issue for now.
