### ISSUE TITLE
Doesn't seem to quite work with ruby 

### ISSUE THREAD

**Issue by tompretty** [jonsamp/codecademy-syntax#3]
Hi,
First off, love the theme. However, the ruby highlighting seems slightly off. 

![screenshot 2](https://user-images.githubusercontent.com/17720442/30439119-d5a2c160-996a-11e7-9385-a918a9b8dc02.png)

It doesn't highlight local variables and formal parameters correctly in that lovely orange. The rhs of the instance variable assignments and call to puts should also be orange.
 
Hope this is an easy fix because the theme is so nice I don't want to use anything else!

**Comment by jonsamp** [comment]
Thanks for the feedback!

This is a relatively simple change, so I will find some time this week to update it. Leaving this issue open until it's fixed 🙌

**Comment by jonsamp** [comment]
Updated the package, so please update when you get a chance!

I wasn't able to get an exact match to the codecademy.com syntax theme, since Atom's syntax selectors are somewhat limited, but it's much closer.

Again, thanks for the feedback. Closing since this has been resolved.
